# Site settings
title: "Portafolio"
email: a.vegaramirez76@gmail.com
description: "Personal blog."
baseurl: ""
url: "https://totovr.github.io"
title_description: "Hello! I'm Antonio Vega Ramirez, current master student in Hiroshima University.
Originally from Guanajuato, Antonio received a BA in Telecommunications and Electronics
engineering from Guanajuato University.

I'm working under the supervision of Professor Kurita in the developing of new soft exoskeletons and human augmentation technology."
title_image: "assets/avatar.JPG"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/totovr/totovr.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: SpainDice
github_username:  totovr
instagram_username: a.vegaramirez
linkedin_link: https://www.linkedin.com/in/totovr/
google_plus_link: https://plus.google.com/u/0/+AntonioVegaAVR
stackoverflow_link: https://stackoverflow.com/users/9060253/antonio-vega

# Footer
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/totovr\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
